apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybefore
  labels:
    app: mybefore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mybefore
      version: v0.0.1
  template:
    metadata:
      labels:
        app: mybefore
        version: v0.0.1
    spec:
      containers:
      - name:   mybefore
        image:  babyshow/mybefore:v0.0.2
        ports:
        - containerPort: 8080