apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: myweb-ingress
spec:
    rules:
    - http:
        paths:
            - path: /
              backend:
                serviceName: mybefore
                servicePort: 8080
            - path: /api
              backend:
                serviceName: mywebtest
                servicePort: 8383